FROM tzahi12345/youtubedl-material:latest

# Install yt-dlp
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install yt-dlp && \
    rm -f /app/node_modules/youtube-dl/bin/youtube-dl && \
    ln -s /usr/local/bin/yt-dlp /app/node_modules/youtube-dl/bin/youtube-dl

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*