services:
  openvpn-yt-dlp:
    image: dperson/openvpn-client
    container_name: openvpn-yt-dlp
    profiles:
      - vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${VPN_OVPN_PATH}:/vpn/credentials.ovpn:ro
      - ./vpn-auth.txt:/vpn/vpn.auth:ro
    ports:
      - "3130:3129/tcp"
      - "8086:17442/tcp"  # YoutubeDL-Material Web UI
    environment:
      - TZ=Europe/Moscow
    security_opt:
      - label:disable
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "8.8.8.8"]
      interval: 30s
      timeout: 10s
      retries: 3

  youtubedl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    profiles:
      - vpn
    depends_on:
      openvpn-yt-dlp:
        condition: service_healthy
    network_mode: "service:openvpn-yt-dlp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      # YoutubeDL-Material settings
      - ytdl_use_local_db=true
      - write_ytdl_config=true
      - ALLOW_CONFIG_MUTATIONS=true
      # Optional settings
      - ytdl_default_theme=${YTDL_THEME:-dark}
      - ytdl_allow_advanced_download=true
      - ytdl_use_cookies_file=true
      - ytdl_cookies_file_path=/app/cookies/cookies.txt
      # Download settings
      - ytdl_default_file_output=/app/downloads/%(title)s.%(ext)s
      # REMOVED rate limit to avoid error
      # - ytdl_download_rate_limit=${RATE_LIMIT:-0}
      # Force yt-dlp usage
      - ytdl_use_yt_dlp=true
      - ytdl_custom_args=--no-check-certificate
    volumes:
      # Main volumes
      - ${DOWNLOAD_DIR}:/app/downloads:rw
      - ./youtubedl-material/config:/app/appdata:rw
      - ./yt-dlp/cookies:/app/cookies:rw
      # Audio/Video folders (optional organization)
      - ${DOWNLOAD_DIR}/audio:/app/audio:rw
      - ${DOWNLOAD_DIR}/video:/app/video:rw
      - ${DOWNLOAD_DIR}/subscriptions:/app/subscriptions:rw
    restart: unless-stopped

  # Alternative: Keep command-line yt-dlp for scripts/automation
  yt-dlp-cli:
    image: thr3a/yt-dlp:latest
    container_name: yt-dlp-cli
    profiles:
      - vpn
      - vpn-cli
    depends_on:
      openvpn-yt-dlp:
        condition: service_healthy
    network_mode: "service:openvpn-yt-dlp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./yt-dlp/config:/config:rw
      - ${DOWNLOAD_DIR}:/downloads:rw
      - ./yt-dlp/cookies:/cookies:rw
      - ./yt-dlp/archive:/archive:rw
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    command: []

  # WITHOUT VPN versions
  youtubedl-material-direct:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    profiles:
      - no-vpn
    ports:
      - "8086:17442/tcp"  # Web UI
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      # YoutubeDL-Material settings
      - ytdl_use_local_db=true
      - write_ytdl_config=true
      - ALLOW_CONFIG_MUTATIONS=true
      # Optional settings
      - ytdl_default_theme=${YTDL_THEME:-dark}
      - ytdl_allow_advanced_download=true
      - ytdl_use_cookies_file=true
      - ytdl_cookies_file_path=/app/cookies/cookies.txt
      # Download settings
      - ytdl_default_file_output=/app/downloads/%(title)s.%(ext)s
      # REMOVED rate limit to avoid error
      # - ytdl_download_rate_limit=${RATE_LIMIT:-0}
      # Force yt-dlp usage
      - ytdl_use_yt_dlp=true
      - ytdl_custom_args=--no-check-certificate
    volumes:
      # Main volumes
      - ${DOWNLOAD_DIR}:/app/downloads:rw
      - ./youtubedl-material/config:/app/appdata:rw
      - ./yt-dlp/cookies:/app/cookies:rw
      # Audio/Video folders (optional organization)
      - ${DOWNLOAD_DIR}/audio:/app/audio:rw
      - ${DOWNLOAD_DIR}/video:/app/video:rw
      - ${DOWNLOAD_DIR}/subscriptions:/app/subscriptions:rw
    restart: unless-stopped