services:
  openvpn-yt-dlp:
    image: dperson/openvpn-client
    container_name: openvpn-yt-dlp
    profiles:
      - vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${VPN_OVPN_PATH}:/vpn/credentials.ovpn:ro
      - ./vpn-auth.txt:/vpn/vpn.auth:ro
    ports:
      - "3130:3129/tcp"
      - "8086:17442/tcp"  # YoutubeDL-Material Web UI
    environment:
      - TZ=Europe/Moscow
    security_opt:
      - label:disable
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "8.8.8.8"]
      interval: 30s
      timeout: 10s
      retries: 3

  # yt-dlp CLI container that provides the binary
  yt-dlp-cli:
    image: thr3a/yt-dlp:latest
    container_name: yt-dlp-cli
    profiles:
      - vpn
    depends_on:
      openvpn-yt-dlp:
        condition: service_healthy
    network_mode: "service:openvpn-yt-dlp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./yt-dlp/config:/config:rw
      - ${DOWNLOAD_DIR}:/downloads:rw
      - ./yt-dlp/cookies:/cookies:rw
      - ./yt-dlp/archive:/archive:rw
      # Share yt-dlp binary location
      - ytdlp-shared-bin:/shared-bin
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "echo 'Copying yt-dlp binary to shared volume...'
      cp /usr/local/bin/yt-dlp /shared-bin/yt-dlp 2>/dev/null || true
      chmod +x /shared-bin/yt-dlp
      echo 'yt-dlp binary shared. Container staying alive...'
      while true; do sleep 3600; done"

  youtubedl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    profiles:
      - vpn
    depends_on:
      openvpn-yt-dlp:
        condition: service_healthy
      yt-dlp-cli:
        condition: service_started
    network_mode: "service:openvpn-yt-dlp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      # YoutubeDL-Material settings
      - ytdl_use_local_db=true
      - write_ytdl_config=true
      - ALLOW_CONFIG_MUTATIONS=true
      # Optional settings
      - ytdl_default_theme=${YTDL_THEME:-dark}
      - ytdl_allow_advanced_download=true
      - ytdl_use_cookies_file=true
      - ytdl_cookies_file_path=/app/cookies/cookies.txt
      # Download settings
      - ytdl_default_file_output=/app/downloads/%(title)s.%(ext)s
    volumes:
      # Main volumes
      - ${DOWNLOAD_DIR}:/app/downloads:rw
      - ./youtubedl-material/config:/app/appdata:rw
      - ./yt-dlp/cookies:/app/cookies:rw
      # Audio/Video folders
      - ${DOWNLOAD_DIR}/audio:/app/audio:rw
      - ${DOWNLOAD_DIR}/video:/app/video:rw
      - ${DOWNLOAD_DIR}/subscriptions:/app/subscriptions:rw
      # Share yt-dlp binary location
      - ytdlp-shared-bin:/shared-bin:ro
      - ./scripts/ytdlm-entrypoint.sh:/custom-entrypoint.sh:ro
    entrypoint: ["/custom-entrypoint.sh"]
    restart: unless-stopped

volumes:
  ytdlp-shared-bin: