services:
  openvpn-yt-dlp:
    image: dperson/openvpn-client
    container_name: openvpn-yt-dlp
    profiles:
      - vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${VPN_OVPN_PATH}:/vpn/credentials.ovpn:ro
      - ./vpn-auth.txt:/vpn/vpn.auth:ro
    ports:
      - "3130:3129/tcp"
      - "8086:8081/tcp"  # Metube Web UI
    environment:
      - TZ=Europe/Moscow
    security_opt:
      - label:disable
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "8.8.8.8"]
      interval: 30s
      timeout: 10s
      retries: 3

  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    profiles:
      - vpn
    depends_on:
      openvpn-yt-dlp:
        condition: service_healthy
    network_mode: "service:openvpn-yt-dlp"
    environment:
      - UID=1000
      - GID=1000
      - DOWNLOAD_DIR=/downloads
      - STATE_DIR=/config
      - DELETE_FILE_ON_TRASHCAN=true
      # Quality settings
      - DEFAULT_THEME=dark
      - OUTPUT_TEMPLATE=%(title)s.%(ext)s
      - YTDL_OPTIONS={"writesubtitles":true,"subtitleslangs":["en","es","fr"],"postprocessors":[{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false}],"format":"bestvideo[height<=?1080]+bestaudio/best"}
    volumes:
      - ${DOWNLOAD_DIR}:/downloads
      - ./metube/config:/config
      # Share cookies if needed
      - ./yt-dlp/cookies:/cookies:ro
    restart: unless-stopped

  # Keep yt-dlp CLI for command-line usage
  yt-dlp-cli:
    image: thr3a/yt-dlp:latest
    container_name: yt-dlp-cli
    profiles:
      - vpn
      - vpn-cli
    depends_on:
      openvpn-yt-dlp:
        condition: service_healthy
    network_mode: "service:openvpn-yt-dlp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./yt-dlp/config:/config:rw
      - ${DOWNLOAD_DIR}:/downloads:rw
      - ./yt-dlp/cookies:/cookies:rw
      - ./yt-dlp/archive:/archive:rw
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    command: []

  # WITHOUT VPN version
  metube-direct:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    profiles:
      - no-vpn
    ports:
      - "8086:8081/tcp"
    environment:
      - UID=1000
      - GID=1000
      - DOWNLOAD_DIR=/downloads
      - STATE_DIR=/config
      - DELETE_FILE_ON_TRASHCAN=true
      # Quality settings
      - DEFAULT_THEME=dark
      - OUTPUT_TEMPLATE=%(title)s.%(ext)s
      - YTDL_OPTIONS={"writesubtitles":true,"subtitleslangs":["en","es","fr"],"postprocessors":[{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false}],"format":"bestvideo[height<=?1080]+bestaudio/best"}
    volumes:
      - ${DOWNLOAD_DIR}:/downloads
      - ./metube/config:/config
      - ./yt-dlp/cookies:/cookies:ro
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Daily at 4 AM
    restart: unless-stopped